spring:
  application:
    name: boki-spring-actuator1
management:
  endpoints: # ??
    web:
      cors:
        allowed-origins: http://test1.com, http://test2.com
        allowed-methods: GET
      exposure:
        include: "*"
