spring:
  application:
    name: boki-spring-actuator1
management:
  endpoints: # 노출
    web:
      exposure:
        include: "*"
  endpoint: # 활성화
    health:
#      show-components: always
      show-details: always
