spring:
  application:
    name: boki-spring-actuator1
management:
  endpoints: # 노출
    web:
      exposure:
        include: "*"
  endpoint: # 활성화
    health:
#      show-components: always
      show-details: always
    env:
      show-values: always # env 변수 노출
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  my-app:
    any-key: someValue
    group-id: "@project.groupId@"
    artifact-id: "@project.artifactId@"
    custom: "@custom.value@"
