@myhost = localhost:8080
// @no-log
// @no-cookie-jar

### GET actuator endpoints
GET http://{{myhost}}/actuator

### GET actuator custom endpoint - Query String
GET http://{{myhost}}/actuator/my-library-info?includeVersion=true

### POST actuator custom endpoint
POST http://{{myhost}}/actuator/my-library-info
Content-Type: application/json

{
  "name": "tests",
  "enableSomething": false
}

### GET actuator custom endpoint - Single Path Variable
GET http://{{myhost}}/actuator/my-library-info/test123

### GET actuator custom endpoint - Multi Path Variable
GET http://{{myhost}}/actuator/my-library-info/test1234/world5678

### Health Endpoint
GET http://{{myhost}}/actuator/health

### Info(Git, Build) Endpoint
GET http://{{myhost}}/actuator/info

### Env Endpoint
GET http://{{myhost}}/actuator/env

### Metric Endpoint
GET http://{{myhost}}/actuator/metrics

### Custom Metric Endpoint1
GET http://{{myhost}}/actuator/metrics/my.stock

### Custom Metric Endpoint2
GET http://{{myhost}}/actuator/metrics/my.product

### Call Count Endpoint
GET http://{{myhost}}/counter/req

### Custom Metric Counter(Counter.builder)
GET http://{{myhost}}/actuator/metrics/my.http.request

### Custom Metric Counter(FunctionCounter.builder)
GET http://{{myhost}}/actuator/metrics/my.function.counter

### Custom Metric Counter(MeterBinder)
GET http://{{myhost}}/actuator/metrics/my.function.counter2

### Call AOP Count Endpoint
GET http://{{myhost}}/counter/counted

### Custom Metric Counter(AOP)
GET http://{{myhost}}/actuator/metrics/my.counter.counted

### Get JVM memory max with heap area by using tag
GET http://{{myhost}}/actuator/metrics/jvm.memory.max?tag=area:heap

### Call Tag push Endpoint
GET http://{{myhost}}/api/tag/push

### Call Tag pop Endpoint
GET http://{{myhost}}/api/tag/pop

### Get Custom Queue Counter Endpoint
GET http://{{myhost}}/actuator/metrics/my.queue.counter

### Get Custom Queue Counter Endpoint with push type by using tag
GET http://{{myhost}}/actuator/metrics/my.queue.counter?tag=type:push

### Get Custom Queue Counter Endpoint with pop type by using tag
GET http://{{myhost}}/actuator/metrics/my.queue.counter?tag=type:pop
