@myhost = localhost:8080
// @no-log
// @no-cookie-jar

### GET actuator endpoints
GET http://{{myhost}}/actuator

### GET actuator custom endpoint - Query String
GET http://{{myhost}}/actuator/my-library-info?includeVersion=true

### POST actuator custom endpoint
POST http://{{myhost}}/actuator/my-library-info
Content-Type: application/json

{
  "name": "tests",
  "enableSomething": false
}

### GET actuator custom endpoint - Single Path Variable
GET http://{{myhost}}/actuator/my-library-info/test123

### GET actuator custom endpoint - Multi Path Variable
GET http://{{myhost}}/actuator/my-library-info/test1234/world5678

### Health Endpoint
GET http://{{myhost}}/actuator/health
